# --- Publishing ------------------------------------------------------------------------------
GROUP=io.github.shivathapaa.kmpads
VERSION_NAME=0.2.0

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/shivathapaa/KMP-Ads
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=shivathapaa
POM_DEVELOPER_NAME=Shiva Thapa
POM_DEVELOPER_URL=https://github.com/shivathapaa/
POM_SCM_URL=https://github.com/shivathapaa/KMP-Ads
POM_SCM_CONNECTION=scm:git:git://github.com/shivathapaa/KMP-Ads.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/shivathapaa/KMP-Ads.git

# --- Gradle ----------------------------------------------------------------------------------
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true

# --- Kotlin ----------------------------------------------------------------------------------
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3G
kotlin.native.binary.gc=cms
kotlin.native.ignoreDisabledTargets=true

# --- Android ---------------------------------------------------------------------------------
android.useAndroidX=true
android.nonTransitiveRClass=true
